#!/bin/bash

#add symlinks
cd /usr/local/cuda-10.2/lib64
sudo ln -s libcusparse.so.10 libcusparse.so.10.0
sudo ln -s libcusolver.so.10 libcusolver.so.10.0
sudo ln -s libcurand.so.10 libcurand.so.10.0
sudo ln -s libcufft.so.10 libcufft.so.10.0
sudo ln -s libcudart.so.10.2 libcudart.so.10.0

# add smylinks
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libcublas.so.10 libcublas.so.10.0

#add environment variables
echo 'export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:/usr/lib/x86_64-linux-gnu/${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}' >> ~/.bashrc 




