#!/bin/bash
cd /usr/local/cuda-10.1/lib64
sudo ln -s libcusparse.so.10 libcusparse.so.10.0
sudo ln -s libcusolver.so.10 libcusolver.so.10.0
sudo ln -s libcurand.so.10 libcurand.so.10.0
sudo ln -s libcufft.so.10 libcufft.so.10.0
sudo ln -s libcudart.so.10.1 libcudart.so.10.0



